FROM centos:centos7
RUN yum update && yum install -y -q wget java-1.8.0-openjdk && yum clean all 
wget https://downloads.typesafe.com/typesafe-activator/1.3.5/typesafe-activator-1.3.5.zip && unzip typesafe-activator-1.3.5.zip /opt/ && rm -f typesafe-activator-1.3.5.zip 

